Merging Audrey's Merged csv with Yra's Database

In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('merged/Merged_Dataset.csv')
df.head()

,Name,SiteDescription,Administrator,Licensee,StreetAddress,City,State,Zip,County,Email,PhoneNumber
0,SOMERMONT FAMILY HOME,ADULT RESIDENTIAL,"KINNAIRD, SUSAN","KINNAIRD, SUSAN",1393 SOMERMONT DRIVE,EL CAJON,CA,92021.0,SAN DIEGO,NaN,(619) 448-8744
1,ST MADELEINE SOPHIES CENTER,ADULT DAY PROGRAM,DEBRA EMERSON,"ST MADELEINE SOPHIES TRAINING CTR, INC",2119 E. MADISON AVENUE,EL CAJON,CA,92019.0,SAN DIEGO,NaN,(619) 442-5129
2,ORANGE WOOD MANOR,ADULT RESIDENTIAL,DEBORAH ALVARADO,JO-VON ENTERPRISES,1202 SOUTH ORANGE,EL CAJON,CA,92020.0,SAN DIEGO,NaN,(619) 440-0121
3,BENEDICT GUEST HOME,ADULT RESIDENTIAL,"DIAZ, DIANA","BENEDICT, GEORGE & RAINEY D.",1728 DAYTON DRIVE,LEMON GROVE,CA,91945.0,SAN DIEGO,NaN,(619) 466-3454
4,VOA - TROY CENTER FOR SUPPORTIVE LIVING,ADULT RESIDENTIAL,NICHOLAS FIERRO,"VOLUNTEERS OF AMERICA, THE",8627 TROY STREET,SPRING VALLEY,CA,91977.0,SAN DIEGO,NaN,(619) 465-8792

In [5]:
df.columns = [c.lower() for c in df.columns]
df = df.rename(columns={'streetaddress': 'address'})

In [6]:
df.head()

,name,sitedescription,administrator,licensee,address,city,state,zip,county,email,phonenumber
0,SOMERMONT FAMILY HOME,ADULT RESIDENTIAL,"KINNAIRD, SUSAN","KINNAIRD, SUSAN",1393 SOMERMONT DRIVE,EL CAJON,CA,92021.0,SAN DIEGO,NaN,(619) 448-8744
1,ST MADELEINE SOPHIES CENTER,ADULT DAY PROGRAM,DEBRA EMERSON,"ST MADELEINE SOPHIES TRAINING CTR, INC",2119 E. MADISON AVENUE,EL CAJON,CA,92019.0,SAN DIEGO,NaN,(619) 442-5129
2,ORANGE WOOD MANOR,ADULT RESIDENTIAL,DEBORAH ALVARADO,JO-VON ENTERPRISES,1202 SOUTH ORANGE,EL CAJON,CA,92020.0,SAN DIEGO,NaN,(619) 440-0121
3,BENEDICT GUEST HOME,ADULT RESIDENTIAL,"DIAZ, DIANA","BENEDICT, GEORGE & RAINEY D.",1728 DAYTON DRIVE,LEMON GROVE,CA,91945.0,SAN DIEGO,NaN,(619) 466-3454
4,VOA - TROY CENTER FOR SUPPORTIVE LIVING,ADULT RESIDENTIAL,NICHOLAS FIERRO,"VOLUNTEERS OF AMERICA, THE",8627 TROY STREET,SPRING VALLEY,CA,91977.0,SAN DIEGO,NaN,(619) 465-8792

In [7]:
df['full_address'] = df['address'].str.title().str.strip()

In [8]:
df.head()

,name,sitedescription,administrator,licensee,address,city,state,zip,county,email,phonenumber,full_address
0,SOMERMONT FAMILY HOME,ADULT RESIDENTIAL,"KINNAIRD, SUSAN","KINNAIRD, SUSAN",1393 SOMERMONT DRIVE,EL CAJON,CA,92021.0,SAN DIEGO,NaN,(619) 448-8744,1393 Somermont Drive
1,ST MADELEINE SOPHIES CENTER,ADULT DAY PROGRAM,DEBRA EMERSON,"ST MADELEINE SOPHIES TRAINING CTR, INC",2119 E. MADISON AVENUE,EL CAJON,CA,92019.0,SAN DIEGO,NaN,(619) 442-5129,2119 E. Madison Avenue
2,ORANGE WOOD MANOR,ADULT RESIDENTIAL,DEBORAH ALVARADO,JO-VON ENTERPRISES,1202 SOUTH ORANGE,EL CAJON,CA,92020.0,SAN DIEGO,NaN,(619) 440-0121,1202 South Orange
3,BENEDICT GUEST HOME,ADULT RESIDENTIAL,"DIAZ, DIANA","BENEDICT, GEORGE & RAINEY D.",1728 DAYTON DRIVE,LEMON GROVE,CA,91945.0,SAN DIEGO,NaN,(619) 466-3454,1728 Dayton Drive
4,VOA - TROY CENTER FOR SUPPORTIVE LIVING,ADULT RESIDENTIAL,NICHOLAS FIERRO,"VOLUNTEERS OF AMERICA, THE",8627 TROY STREET,SPRING VALLEY,CA,91977.0,SAN DIEGO,NaN,(619) 465-8792,8627 Troy Street

In [9]:
df.to_csv('merged/Merged_Dataset_clean.csv', index=False)
print('Saved, rows:', len(df))

Saved, rows: 128751

In [10]:
pd.read_csv('merged/mission_aligned.csv')

,name,address,zip_code,type,administrator,phonenumber,source,entity_type
0,1LIFE HEALTHCARE INC DBA ONE MEDICAL,7740 El Camino Real,NaN,DOCTOR/OSTEOPA/CHIRO,C/O ADVANTAX,NaN,Audrey Merged,NaN
1,1LIFE HEALTHCARE INC DBA ONE MEDICAL,4505 La Jolla Village Dr,NaN,DOCTOR/OSTEOPA/CHIRO,C/O ADVANTAX,NaN,Audrey Merged,NaN
2,1LIFE HEALTHCARE INC DBA ONE MEDICAL,1230 Columbia St,NaN,DOCTOR/OSTEOPA/CHIRO,C/O ADVANTAX,NaN,Audrey Merged,NaN
3,2419 29TH STREET LLC/LSR NEW BEGINNINGS COMMUN...,9625 Black Mountain Rd,NaN,EXEMPT LESSOR,C/O JOHN BOLS,NaN,Audrey Merged,NaN
4,3M HEALTHCARE OPCO LLC,12330 Crosthwaite Cir,NaN,MFG HEAVY,C/O RYAN LLC,NaN,Audrey Merged,NaN
...,...,...,...,...,...,...,...,...
1208,ZAP ENERGY INC,1320 Grand Ave,NaN,MFG LIGHT,C/O BRIAN NELSON,NaN,Audrey Merged,NaN
1209,ZOETIS LLC ANIMAL HEALTH DIVISION,16420 Via Esprillo,NaN,MISC & TECHNICAL LAB,C/O RYAN LLC,NaN,Audrey Merged,NaN
1210,24346-Brookdale Clairemont,5219 Clairemont Mesa Blvd,92117.0,Senior Living Community,"PIERFAX, JUDITH",(858) 292-8044,Energy Building,For Profit
1211,60077- Sunrise of Sabre Springs,12515 Springhurst Dr,92128.0,Senior Living Community,ROBERT DAYNESS,(858) 391-9160,Energy Building,For Profit
1212,810 Turquoise St,810 Turquoise St,92109.0,Senior Living Community,"RICHARDSON, PAUL",(858) 488-4300,Energy Building,For Profit