In [1]:
import requests
import pandas as pd
import json
import time

COOKIE = "_fbp=fb.1.1776298207315.209786966661945786; pscd=join.zeffy.com; _tt_enable_cookie=1; _ttp=01KP9SZD99V5H10MW4A091K69V_.tt.1; hubspotutk=67584e2a1aa2da0738ba3799c1b4a7ad; _ga=GA1.1.753230627.1776298209; _dcid=dcid.1.1777483418711.567023890; _gtmeec=e30%3D; AMP_MKTG_ef17265876=JTdCJTdE; __hssrc=1; zeffy_jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxYzI5MDczOC1hNWMyLTQwOGQtYmEyYy04YTJhY2M2NTBkMWQiLCJvcmdhbml6YXRpb25JZCI6IjRkMWJmMGM0LWE4ZGEtNDRmOC04MDU2LWNhNjJkMzE0NTdmYiIsImlhdCI6MTc3ODU2MTI5MCwiZXhwIjoxNzc4NjQ3NjkwfQ.abWIA5WDSaii63jjJjfJur7EEc83R5eJHb_1w3yFsEM; _clck=xb65wy%5E2%5Eg67%5E0%5E2303; __hstc=251809558.67584e2a1aa2da0738ba3799c1b4a7ad.1776298210925.1778715380731.1779305940219.15; _rdt_uuid=1776298207503.a1ce3103-7442-496b-9fdf-76207dc57c04; _uetsid=8c400ec0548311f1ba168766b99196ee; _uetvid=a20df030392811f18d6b9357c29f4f8b; _ga_00000000=GS2.1.s1779305940$o15$g0$t1779306602$j28$l0$h0; __hssc=251809558.4.1779305940219; ttcsid_D1RCEIJC77U6050D1T5G=1779305938857::NYSaIvxwCbk1kfI797bR.18.1779306645432.1; _clsk=15lvpbc%5E1779306645974%5E12%5E1%5Ea.clarity.ms%2Fcollect; _ga_173QX444NK=GS2.1.s1779305938$o21$g1$t1779306646$j43$l0$h0; _gcl_au=1.1.1461337013.1776298207.551747082.1779305940.1779306646; ttcsid=1779305938857::1FEGjpJKP3fTIYdN17UT.18.1779306645432.0::1.706551.663017::706534.9.59.425::1166202.112.0; AMP_ef17265876=JTdCJTIyZGV2aWNlSWQlMjIlM0ElMjJjYmI3ZTY2Yy03MzcyLTQ2ZjQtYjhhNC1kNjE1YjdmYWMyZjglMjIlMkMlMjJ1c2VySWQlMjIlM0ElMjIxYzI5MDczOC1hNWMyLTQwOGQtYmEyYy04YTJhY2M2NTBkMWQlMjIlMkMlMjJzZXNzaW9uSWQlMjIlM0ExNzc5MzA1OTM4OTI3JTJDJTIyb3B0T3V0JTIyJTNBZmFsc2UlMkMlMjJsYXN0RXZlbnRUaW1lJTIyJTNBMTc3OTMwNzI0MzcxNSUyQyUyMmxhc3RFdmVudElkJTIyJTNBMTgwMSUyQyUyMnBhZ2VDb3VudGVyJTIyJTNBMCUyQyUyMmNvb2tpZURvbWFpbiUyMiUzQSUyMi56ZWZmeS5jb20lMjIlN0Q=; session_jwt=eyJhbGciOiJSUzI1NiIsImtpZCI6Imp3ay1saXZlLWM3NjIwNjlhLTI1NGQtNGVlNi1hZjBkLTI0ODFlYTlmNmYzYyIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicHJvamVjdC1saXZlLWM1NzkxZDVhLWZhMzgtNDk2Mi1hNTFkLWFhZTllOTZlM2VmZiJdLCJleHAiOjE3NzkzMDc3NDksImh0dHBzOi8vc3R5dGNoLmNvbS9vcmdhbml6YXRpb24iOnsib3JnYW5pemF0aW9uX2lkIjoib3JnYW5pemF0aW9uLWxpdmUtYjA2NTM0OWUtMzY1NC00NmE3LWJhYjItZGNkNjQwYWM4NzI0Iiwic2x1ZyI6Ijc2OWJiZTg4LTIzZGUtNDYwOS04ZWM4LTQ5MWE3YTMwZmY4ZCJ9LCJodHRwczovL3N0eXRjaC5jb20vc2Vzc2lvbiI6eyJpZCI6Im1lbWJlci1zZXNzaW9uLWxpdmUtZjY0ZDc1YzItMzZkZi00ZGJmLTk0NzItYjIwNjhiZjNiOTgwIiwic3RhcnRlZF9hdCI6IjIwMjYtMDUtMTJUMDQ6NTM6MTlaIiwibGFzdF9hY2Nlc3NlZF9hdCI6IjIwMjYtMDUtMjBUMjA6MDQ6MDlaIiwiZXhwaXJlc19hdCI6IjIwMjYtMTEtMDhUMDQ6NTM6MTlaIiwiYXR0cmlidXRlcyI6eyJ1c2VyX2FnZW50IjoiIiwiaXBfYWRkcmVzcyI6IiJ9LCJhdXRoZW50aWNhdGlvbl9mYWN0b3JzIjpbeyJ0eXBlIjoicGFzc3dvcmQiLCJkZWxpdmVyeV9tZXRob2QiOiJrbm93bGVkZ2UiLCJsYXN0X2F1dGhlbnRpY2F0ZWRfYXQiOiIyMDI2LTA1LTEyVDA0OjQ4OjEwWiJ9LHsidHlwZSI6Im90cCIsImRlbGl2ZXJ5X21ldGhvZCI6InNtcyIsImxhc3RfYXV0aGVudGljYXRlZF9hdCI6IjIwMjYtMDUtMTJUMDQ6NTM6MTlaIiwicGhvbmVfbnVtYmVyX2ZhY3RvciI6eyJwaG9uZV9pZCI6Im1lbWJlci1waG9uZS1udW1iZXItbGl2ZS1hNDdkOTBiNy1mNWQ2LTRiNTktODJiZS1lYjVjMGMzODZkZjMiLCJwaG9uZV9udW1iZXIiOiIrMTk0OTUwMTU0MjMifX1dLCJyb2xlcyI6WyJzdHl0Y2hfbWVtYmVyIl19LCJpYXQiOjE3NzkzMDc0NDksImlzcyI6InN0eXRjaC5jb20vcHJvamVjdC1saXZlLWM1NzkxZDVhLWZhMzgtNDk2Mi1hNTFkLWFhZTllOTZlM2VmZiIsIm5iZiI6MTc3OTMwNzQ0OSwic3ViIjoibWVtYmVyLWxpdmUtYjM3MGMxMWQtYzQ1Mi00YmIxLTgyNDEtMmNiMDMwZjZhZTc2In0.gHVSiUbBOyBgHZiTP0cEB976rwj7tf_NsGYocU9laCzEPiOYeXWSi1iP5rVlACXRJDO79zRiA61a1rJ8-_jXhz75KL5XL-wPtAHbqojf0gPjHmZCwnt6r0UiTWeUwAcZPZySJGwmtUVGlsnpGXl7Gakk4JNflkYhw1gDillktFk8J5B-JDQntnet_Lzb0MUvbBKvUAt7-_EXyEjZpllxf_NFxqOJfnNCGotLMzYF9DwTlcYJnLzQyYMvaCUQ0RdzcWvPH1nXDaDZWSMlSTPJ0gHLKUTy-Nx7RXs5XfGripCwjgwWIYIIDwqqXuQNTCZMb1CSF9whIA5h8XNY7I8_Zg"

EMAIL_DELIVERY_ID = "cf138476-aff6-4133-9070-7c79dc3f36c3"

URL = "https://api.zeffy.com/_new/trpc/getEmails"

headers = {
    "cookie": COOKIE,
    "accept": "application/json",
    "origin": "https://www.zeffy.com",
    "referer": "https://www.zeffy.com/"
}


def get_zeffy_contacts(status, limit=100):
    all_items = []
    cursor = 0

    while True:
        payload = {
            "emailDeliveryId": EMAIL_DELIVERY_ID,
            "limit": limit,
            "emailStatuses": [status],
            "cursor": cursor
        }

        params = {
            "input": json.dumps(payload)
        }

        r = requests.get(URL, headers=headers, params=params)

        print(f"{status} | cursor={cursor} | status_code={r.status_code}")

        if r.status_code != 200:
            print(r.text)
            break

        data = r.json()

        items = data["result"]["data"]["items"]

        if len(items) == 0:
            break

        all_items.extend(items)

        if len(items) < limit:
            break

        cursor += limit
        time.sleep(0.2)

    df = pd.DataFrame(all_items)
    return df

In [2]:
df_delivered = get_zeffy_contacts("Delivered")
df_bounced = get_zeffy_contacts("Bounced")
df_clicked = get_zeffy_contacts("Clicked")
df_unsubscribed = get_zeffy_contacts("Unsubscribed")

Delivered | cursor=0 | status_code=200
Delivered | cursor=100 | status_code=200
Delivered | cursor=200 | status_code=200
Delivered | cursor=300 | status_code=200
Delivered | cursor=400 | status_code=200
Bounced | cursor=0 | status_code=200
Bounced | cursor=100 | status_code=200
Bounced | cursor=200 | status_code=200
Bounced | cursor=300 | status_code=200
Bounced | cursor=400 | status_code=200
Bounced | cursor=500 | status_code=200
Bounced | cursor=600 | status_code=200
Bounced | cursor=700 | status_code=200
Bounced | cursor=800 | status_code=200
Bounced | cursor=900 | status_code=200
Bounced | cursor=1000 | status_code=200
Bounced | cursor=1100 | status_code=200
Bounced | cursor=1200 | status_code=200
Bounced | cursor=1300 | status_code=200
Bounced | cursor=1400 | status_code=200
Bounced | cursor=1500 | status_code=200
Bounced | cursor=1600 | status_code=200
Bounced | cursor=1700 | status_code=200
Bounced | cursor=1800 | status_code=200
Bounced | cursor=1900 | status_code=200
Bounced | cursor=2000 | status_code=200
Bounced | cursor=2100 | status_code=200
Bounced | cursor=2200 | status_code=200
Bounced | cursor=2300 | status_code=200
Bounced | cursor=2400 | status_code=200
Bounced | cursor=2500 | status_code=200
Bounced | cursor=2600 | status_code=200
Bounced | cursor=2700 | status_code=200
Bounced | cursor=2800 | status_code=200
Bounced | cursor=2900 | status_code=200
Bounced | cursor=3000 | status_code=200
Bounced | cursor=3100 | status_code=200
Bounced | cursor=3200 | status_code=200
Bounced | cursor=3300 | status_code=200
Bounced | cursor=3400 | status_code=200
Bounced | cursor=3500 | status_code=200
Bounced | cursor=3600 | status_code=200
Bounced | cursor=3700 | status_code=200
Bounced | cursor=3800 | status_code=200
Clicked | cursor=0 | status_code=200
Unsubscribed | cursor=0 | status_code=200

In [3]:
df_bounced

,id,contactId,contactEmail,status,contactFirstName,contactLastName
0,9a414715-01f6-4de7-af0c-84e6f120ad6e,8daae30f-4f86-42c5-bf8a-94be8b94995a,aaron.clark@reach360utah.org,Bounced,aaron,clark
1,a89afeb8-a9bf-4174-b3df-a73bab6655a7,7824a6db-6f48-452f-8443-faa8a26d6d37,aaron.dishno@sgyc.org,Bounced,aaron,dishno
2,80aee359-ef1a-4416-98db-ff8b0614164f,ccf07ff6-5c15-406c-881b-4bf42faf49f1,aaron.ling@ymcasd.org,Bounced,aaron,ling
3,7fc45412-45dc-4e89-894a-0312ce58b60b,660495ce-fcab-4425-bdd5-29b4008d7492,aaron.magdaleno@sdarchitecture.org,Bounced,aaron,magdaleno
4,d2fae9b1-505b-4703-9104-d44001ab63f7,07c14ed9-f66a-4471-a5f3-eb61be908308,aaron.wiegman@fpasandiego.org,Bounced,aaron,wiegman
...,...,...,...,...,...,...
3888,bc7d6f06-d6c6-4ba7-b493-e9f0f3b9b424,5e289bfe-83c0-4a44-9f37-f6d26f2c385a,zach.myers@connect.org,Bounced,zach,myers
3889,e593e4f6-75aa-4761-b25c-caac3bf4408c,50f273fe-1db6-49eb-8992-e9e243400d26,zawadski.jana@hipsandiego.org,Bounced,zawadski,jana
3890,1c8857f6-6a6c-4ce0-9d47-61d2ffe95d90,5bf3bc43-914f-46d3-a2fa-0b1823f47ecb,zeke.rodriguez@sdbigs.org,Bounced,zeke,rodriguez
3891,d691675a-a2a8-40c5-97ad-599f647b1671,68eb10c7-a599-4bc2-bba2-2dd35feabd4c,ziad.asghar@evonexus.org,Bounced,ziad,asghar
3892,5ce6b60b-3cf2-4a84-854c-cf4ce1978bed,ed977951-13a8-403b-bbac-e2ef7b168963,zoraida.payne@historickensington.org,Bounced,zoraida,payne

In [4]:
df_clicked

,id,contactId,contactEmail,status,contactFirstName,contactLastName
0,b358a6dc-acb9-41f6-b2b5-28acc003fe2f,76e4b94f-4c65-4190-ab01-233fa242320b,aaron.garrett@seiu221.org,Clicked,aaron,garrett
1,4d633b89-7ec5-4a5e-955a-a9f6e5bb3c3d,cb85dac7-fe35-477d-8fe4-3c9e098fbd69,alma.aguirre@seiu221.org,Clicked,alma,aguirre
2,a36902e7-fa62-4f52-b3b3-01e9620c4acc,bec85977-d9a1-497c-b94d-547515b8c42b,belinda.williamson@es3inc.com,Clicked,belinda,williamson
3,1b9d8066-5281-429a-9c3f-65dcec56134e,00f547c3-8ba3-4789-ab48-42b448101c3b,ben.clay@midway.org,Clicked,ben,clay
4,5254efd4-b3a4-4632-be7b-96abbb4c6c2e,717119dc-42e6-4ca8-a9ba-d9e5408e721a,brett.bailey@es3inc.com,Clicked,brett,bailey
5,eca33254-620f-40d4-a079-b60ae95237a2,5ee03fdf-6b0f-4256-b74a-67067a2a6746,christopher.taylor@seiu221.org,Clicked,christopher,taylor
6,16ded515-eb62-41d9-89e1-7188c4dca6e1,f1af75c9-e9c1-4b38-bd19-8c10d00db9c2,ciani.palencia@seiu221.org,Clicked,ciani,palencia
7,d8a9a3aa-0105-44f5-a301-083f9f64cadb,235605bd-aeb6-4be3-8519-0eeb70faaffb,crystal.irving@seiu221.org,Clicked,crystal,irving
8,53b148c9-3e37-4ef0-bdc4-68f059220011,5e7d2e95-b690-4c0f-a32d-e205381211e7,david.koontz@midway.org,Clicked,david,koontz
9,d2eea80d-6831-4350-a498-ce05135abe60,44a7a42a-f2e1-43a2-8564-88ec5bf8f182,elena.long@seiu221.org,Clicked,elena,long
10,7902b218-3e70-4011-b84c-967626ef73bf,5ce62ffc-75d1-4bce-bfc0-83ffe2164ce5,ellen.minteer@sandiegorowing.org,Clicked,ellen,minteer
11,5d2c704b-0239-4964-bc0e-e823b26703ef,8794ead5-83a8-40b6-a771-976cea9d5822,iris.trammel@seiu221.org,Clicked,iris,trammel
12,061507bd-1238-4c3d-893a-2b2a2a45aa37,7932d3c2-4de9-4777-807d-98ee8f4e0b9e,jennifer.esquivel@seiu221.org,Clicked,jennifer,esquivel
13,1045a87d-324f-4b9f-be05-7a38e0ece9da,17e40c47-90cf-4964-a77e-04f5818083f7,jon.ryan@midway.org,Clicked,jon,ryan
14,db70f175-128c-4bc3-ad86-b461fdf49d97,3e82785b-cd07-456a-add4-234aed1ea954,liane.morton@midway.org,Clicked,liane,morton
15,3cfed64b-9756-4314-9d8f-7a995859ba4d,00c98454-0bcd-4308-abfe-06dbe9bfc9e4,linda.correa@seiu221.org,Clicked,linda,correa
16,89a801f9-02b0-4d3f-bbef-0bbe47573198,e0db03ab-af50-4d16-8763-77789ff22120,lisa.record@wfw.org,Clicked,lisa,record
17,b2557cd1-9c48-44b8-86a0-8940b44f9fb8,04200493-0f5a-40bf-ab7e-1d8a4638732f,luke.pelessone@es3inc.com,Clicked,luke,pelessone
18,d754260a-fc55-4cae-b916-eefcdf9a8ca9,172e9070-dce0-4d87-aa92-a91b6e329a49,marc.pelessone@es3inc.com,Clicked,marc,pelessone
19,3496626e-0add-4653-ac68-242c7a464615,2f96d72c-1221-4b22-b6a7-441406ab1b72,mark.berlin@midway.org,Clicked,mark,berlin
20,2cbc437b-2738-4100-a1d8-805bb939ce66,54aca80f-a63c-42a3-abb5-d502cf6d6ff3,matthew.casas@seiu221.org,Clicked,matthew,casas
21,eb8baf95-922d-4641-9a1b-3e1c3a607bca,b602b185-427a-417d-874d-347155314f8b,nathan.wollmann@seiu221.org,Clicked,nathan,wollmann
22,adce6d72-4224-4f28-ae52-08fef0516574,03d68744-2933-49b7-b0c2-a6e543a0cc2f,richard.thompson@seiu221.org,Clicked,richard,thompson
23,e03e62c1-7376-48c0-8438-1f0ab67dec6c,151da6db-8073-41a5-b255-774d5f909919,teri.sgammato@es3inc.com,Clicked,teri,sgammato
24,71769ff0-574c-489b-9e3c-ae67c42cafc3,dbcca2e2-88d9-4e29-8fc3-8754eb44e1bb,trudi.lang@midway.org,Clicked,trudi,lang
25,65d9022d-7767-4b3d-8349-a31155171f13,4c24fb51-fef2-44d6-a5c5-4cfe983e7af3,vanessa.garcia@seiu221.org,Clicked,vanessa,garcia
26,2b601095-1363-445a-8fc1-1da90859242e,cd582bdf-801a-4f33-a796-6ba70a446d71,zonyea.avery@seiu221.org,Clicked,zonyea,avery

In [5]:
df_delivered

,id,contactId,contactEmail,status,contactFirstName,contactLastName
0,2d5d4c7f-1ec5-432c-b436-e2821d343d37,4b5557b7-4a29-4a9d-89bf-3b09734128cc,aaron.pingel@rihwtf.com,Delivered,aaron,pingel
1,50437fbc-4848-4bbf-881d-77194c3f5693,ecf617db-9868-4c07-881c-a56553620c0d,adam.falk@borderpartnership.org,Delivered,adam,falk
2,6b71c605-b675-4567-bb0d-e1fef2cece51,0a295aa7-177f-4ea9-a795-0b827f4b9225,aditi.salvi@realitychangers.org,Delivered,aditi,salvi
3,b62d3813-3760-4515-a4b0-47cadd42cdc4,ca3ba173-ab95-4e25-917c-23bb5f0cc58e,alan.grant@sandiegoriver.org,Delivered,alan,grant
4,77383381-5498-41c2-8a42-6b0963b53297,4f1c2696-0046-47a9-99e1-97d059ed7cf0,albert.pleskus@sdyc.org,Delivered,albert,pleskus
...,...,...,...,...,...,...
442,adce6d72-4224-4f28-ae52-08fef0516574,03d68744-2933-49b7-b0c2-a6e543a0cc2f,richard.thompson@seiu221.org,Clicked,richard,thompson
443,e03e62c1-7376-48c0-8438-1f0ab67dec6c,151da6db-8073-41a5-b255-774d5f909919,teri.sgammato@es3inc.com,Clicked,teri,sgammato
444,71769ff0-574c-489b-9e3c-ae67c42cafc3,dbcca2e2-88d9-4e29-8fc3-8754eb44e1bb,trudi.lang@midway.org,Clicked,trudi,lang
445,65d9022d-7767-4b3d-8349-a31155171f13,4c24fb51-fef2-44d6-a5c5-4cfe983e7af3,vanessa.garcia@seiu221.org,Clicked,vanessa,garcia
446,2b601095-1363-445a-8fc1-1da90859242e,cd582bdf-801a-4f33-a796-6ba70a446d71,zonyea.avery@seiu221.org,Clicked,zonyea,avery

In [6]:
df_unsubscribed

Empty DataFrame
Columns: []
Index: []

In [7]:
import requests
import pandas as pd
import json
import time

COOKIE = "_fbp=fb.1.1776298207315.209786966661945786; pscd=join.zeffy.com; _tt_enable_cookie=1; _ttp=01KP9SZD99V5H10MW4A091K69V_.tt.1; hubspotutk=67584e2a1aa2da0738ba3799c1b4a7ad; _ga=GA1.1.753230627.1776298209; _dcid=dcid.1.1777483418711.567023890; _gtmeec=e30%3D; AMP_MKTG_ef17265876=JTdCJTdE; __hssrc=1; zeffy_jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxYzI5MDczOC1hNWMyLTQwOGQtYmEyYy04YTJhY2M2NTBkMWQiLCJvcmdhbml6YXRpb25JZCI6IjRkMWJmMGM0LWE4ZGEtNDRmOC04MDU2LWNhNjJkMzE0NTdmYiIsImlhdCI6MTc3ODU2MTI5MCwiZXhwIjoxNzc4NjQ3NjkwfQ.abWIA5WDSaii63jjJjfJur7EEc83R5eJHb_1w3yFsEM; _clck=xb65wy%5E2%5Eg67%5E0%5E2303; __hstc=251809558.67584e2a1aa2da0738ba3799c1b4a7ad.1776298210925.1778715380731.1779305940219.15; _rdt_uuid=1776298207503.a1ce3103-7442-496b-9fdf-76207dc57c04; _uetsid=8c400ec0548311f1ba168766b99196ee; _uetvid=a20df030392811f18d6b9357c29f4f8b; _ga_00000000=GS2.1.s1779305940$o15$g0$t1779306602$j28$l0$h0; __hssc=251809558.4.1779305940219; ttcsid_D1RCEIJC77U6050D1T5G=1779305938857::NYSaIvxwCbk1kfI797bR.18.1779306645432.1; _clsk=15lvpbc%5E1779306645974%5E12%5E1%5Ea.clarity.ms%2Fcollect; _ga_173QX444NK=GS2.1.s1779305938$o21$g1$t1779306646$j43$l0$h0; _gcl_au=1.1.1461337013.1776298207.551747082.1779305940.1779306646; ttcsid=1779305938857::1FEGjpJKP3fTIYdN17UT.18.1779306645432.0::1.706551.663017::706534.9.59.425::1166202.112.0; AMP_ef17265876=JTdCJTIyZGV2aWNlSWQlMjIlM0ElMjJjYmI3ZTY2Yy03MzcyLTQ2ZjQtYjhhNC1kNjE1YjdmYWMyZjglMjIlMkMlMjJ1c2VySWQlMjIlM0ElMjIxYzI5MDczOC1hNWMyLTQwOGQtYmEyYy04YTJhY2M2NTBkMWQlMjIlMkMlMjJzZXNzaW9uSWQlMjIlM0ExNzc5MzA1OTM4OTI3JTJDJTIyb3B0T3V0JTIyJTNBZmFsc2UlMkMlMjJsYXN0RXZlbnRUaW1lJTIyJTNBMTc3OTMwNzI0MzcxNSUyQyUyMmxhc3RFdmVudElkJTIyJTNBMTgwMSUyQyUyMnBhZ2VDb3VudGVyJTIyJTNBMCUyQyUyMmNvb2tpZURvbWFpbiUyMiUzQSUyMi56ZWZmeS5jb20lMjIlN0Q=; session_jwt=eyJhbGciOiJSUzI1NiIsImtpZCI6Imp3ay1saXZlLWM3NjIwNjlhLTI1NGQtNGVlNi1hZjBkLTI0ODFlYTlmNmYzYyIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicHJvamVjdC1saXZlLWM1NzkxZDVhLWZhMzgtNDk2Mi1hNTFkLWFhZTllOTZlM2VmZiJdLCJleHAiOjE3NzkzMDc3NDksImh0dHBzOi8vc3R5dGNoLmNvbS9vcmdhbml6YXRpb24iOnsib3JnYW5pemF0aW9uX2lkIjoib3JnYW5pemF0aW9uLWxpdmUtYjA2NTM0OWUtMzY1NC00NmE3LWJhYjItZGNkNjQwYWM4NzI0Iiwic2x1ZyI6Ijc2OWJiZTg4LTIzZGUtNDYwOS04ZWM4LTQ5MWE3YTMwZmY4ZCJ9LCJodHRwczovL3N0eXRjaC5jb20vc2Vzc2lvbiI6eyJpZCI6Im1lbWJlci1zZXNzaW9uLWxpdmUtZjY0ZDc1YzItMzZkZi00ZGJmLTk0NzItYjIwNjhiZjNiOTgwIiwic3RhcnRlZF9hdCI6IjIwMjYtMDUtMTJUMDQ6NTM6MTlaIiwibGFzdF9hY2Nlc3NlZF9hdCI6IjIwMjYtMDUtMjBUMjA6MDQ6MDlaIiwiZXhwaXJlc19hdCI6IjIwMjYtMTEtMDhUMDQ6NTM6MTlaIiwiYXR0cmlidXRlcyI6eyJ1c2VyX2FnZW50IjoiIiwiaXBfYWRkcmVzcyI6IiJ9LCJhdXRoZW50aWNhdGlvbl9mYWN0b3JzIjpbeyJ0eXBlIjoicGFzc3dvcmQiLCJkZWxpdmVyeV9tZXRob2QiOiJrbm93bGVkZ2UiLCJsYXN0X2F1dGhlbnRpY2F0ZWRfYXQiOiIyMDI2LTA1LTEyVDA0OjQ4OjEwWiJ9LHsidHlwZSI6Im90cCIsImRlbGl2ZXJ5X21ldGhvZCI6InNtcyIsImxhc3RfYXV0aGVudGljYXRlZF9hdCI6IjIwMjYtMDUtMTJUMDQ6NTM6MTlaIiwicGhvbmVfbnVtYmVyX2ZhY3RvciI6eyJwaG9uZV9pZCI6Im1lbWJlci1waG9uZS1udW1iZXItbGl2ZS1hNDdkOTBiNy1mNWQ2LTRiNTktODJiZS1lYjVjMGMzODZkZjMiLCJwaG9uZV9udW1iZXIiOiIrMTk0OTUwMTU0MjMifX1dLCJyb2xlcyI6WyJzdHl0Y2hfbWVtYmVyIl19LCJpYXQiOjE3NzkzMDc0NDksImlzcyI6InN0eXRjaC5jb20vcHJvamVjdC1saXZlLWM1NzkxZDVhLWZhMzgtNDk2Mi1hNTFkLWFhZTllOTZlM2VmZiIsIm5iZiI6MTc3OTMwNzQ0OSwic3ViIjoibWVtYmVyLWxpdmUtYjM3MGMxMWQtYzQ1Mi00YmIxLTgyNDEtMmNiMDMwZjZhZTc2In0.gHVSiUbBOyBgHZiTP0cEB976rwj7tf_NsGYocU9laCzEPiOYeXWSi1iP5rVlACXRJDO79zRiA61a1rJ8-_jXhz75KL5XL-wPtAHbqojf0gPjHmZCwnt6r0UiTWeUwAcZPZySJGwmtUVGlsnpGXl7Gakk4JNflkYhw1gDillktFk8J5B-JDQntnet_Lzb0MUvbBKvUAt7-_EXyEjZpllxf_NFxqOJfnNCGotLMzYF9DwTlcYJnLzQyYMvaCUQ0RdzcWvPH1nXDaDZWSMlSTPJ0gHLKUTy-Nx7RXs5XfGripCwjgwWIYIIDwqqXuQNTCZMb1CSF9whIA5h8XNY7I8_Zg"

EMAIL_DELIVERY_ID = "14351e34-1c5e-40d7-8a88-bf3a6367f80b"

URL = "https://api.zeffy.com/_new/trpc/getEmails"

headers = {
    "cookie": COOKIE,
    "accept": "application/json",
    "origin": "https://www.zeffy.com",
    "referer": "https://www.zeffy.com/"
}


def get_zeffy_contacts2(status, limit=100):
    all_items = []
    cursor = 0

    while True:
        payload = {
            "emailDeliveryId": EMAIL_DELIVERY_ID,
            "limit": limit,
            "emailStatuses": [status],
            "cursor": cursor
        }

        params = {
            "input": json.dumps(payload)
        }

        r = requests.get(URL, headers=headers, params=params)

        print(f"{status} | cursor={cursor} | status_code={r.status_code}")

        if r.status_code != 200:
            print(r.text)
            break

        data = r.json()

        items = data["result"]["data"]["items"]

        if len(items) == 0:
            break

        all_items.extend(items)

        if len(items) < limit:
            break

        cursor += limit
        time.sleep(0.2)

    df = pd.DataFrame(all_items)
    return df

In [8]:
df_delivered2 = get_zeffy_contacts2("Delivered")
df_bounced2 = get_zeffy_contacts2("Bounced")
df_clicked2 = get_zeffy_contacts2("Clicked")
df_unsubscribed2 = get_zeffy_contacts2("Unsubscribed")

Delivered | cursor=0 | status_code=200
Delivered | cursor=100 | status_code=200
Delivered | cursor=200 | status_code=200
Delivered | cursor=300 | status_code=200
Delivered | cursor=400 | status_code=200
Delivered | cursor=500 | status_code=200
Bounced | cursor=0 | status_code=200
Bounced | cursor=100 | status_code=200
Bounced | cursor=200 | status_code=200
Bounced | cursor=300 | status_code=200
Bounced | cursor=400 | status_code=200
Bounced | cursor=500 | status_code=200
Bounced | cursor=600 | status_code=200
Bounced | cursor=700 | status_code=200
Bounced | cursor=800 | status_code=200
Bounced | cursor=900 | status_code=200
Bounced | cursor=1000 | status_code=200
Bounced | cursor=1100 | status_code=200
Bounced | cursor=1200 | status_code=200
Bounced | cursor=1300 | status_code=200
Bounced | cursor=1400 | status_code=200
Bounced | cursor=1500 | status_code=200
Bounced | cursor=1600 | status_code=200
Bounced | cursor=1700 | status_code=200
Bounced | cursor=1800 | status_code=200
Bounced | cursor=1900 | status_code=200
Bounced | cursor=2000 | status_code=200
Bounced | cursor=2100 | status_code=200
Bounced | cursor=2200 | status_code=200
Bounced | cursor=2300 | status_code=200
Bounced | cursor=2400 | status_code=200
Bounced | cursor=2500 | status_code=200
Bounced | cursor=2600 | status_code=200
Bounced | cursor=2700 | status_code=200
Bounced | cursor=2800 | status_code=200
Bounced | cursor=2900 | status_code=200
Bounced | cursor=3000 | status_code=200
Bounced | cursor=3100 | status_code=200
Bounced | cursor=3200 | status_code=200
Bounced | cursor=3300 | status_code=200
Bounced | cursor=3400 | status_code=200
Bounced | cursor=3500 | status_code=200
Bounced | cursor=3600 | status_code=200
Bounced | cursor=3700 | status_code=200
Bounced | cursor=3800 | status_code=200
Bounced | cursor=3900 | status_code=200
Clicked | cursor=0 | status_code=200
Unsubscribed | cursor=0 | status_code=200

In [9]:
df_bounced2

,id,contactId,contactEmail,status,contactFirstName,contactLastName
0,9d8b46cc-9945-4e7d-8e46-bf1f7c2f30a4,6932cc6c-2fa7-484f-9760-0e6c2cda25ae,aad.elzen@cleantechsandiego.org,Bounced,aad,elzen
1,9644946e-495a-4a6d-944c-0a9cc027772b,62d2ff7f-8dc3-4d9a-a02f-4bde7cd9699f,aaron.carr@namisandiego.org,Bounced,aaron,carr
2,fd17876b-ab10-48f8-8e84-bca2195962e1,94e2a0bf-3be1-4685-b647-0131209294d8,aaron.degroot@boysandgirlsfoundation.org,Bounced,aaron,degroot
3,33f6b9c0-17df-43e0-876b-94376f5cfcc6,59cd8a0f-8d7b-4869-862b-113040892f04,aaron.feves@hssailing.org,Bounced,aaron,feves
4,64fdd06b-8361-40ce-9520-1193fe9e5b33,ca1fca5d-0ef5-4a1f-b371-8d2d0350d87f,aaron.franz@meals-on-wheels.org,Bounced,aaron,franz
...,...,...,...,...,...,...
3909,1edc274c-0a13-4bd7-994b-7c748b94b5a2,305fb0e7-bcd6-42bf-82d8-8a71d2074cfe,zalman.carlebach@chabaddowntown.com,Bounced,zalman,carlebach
3910,009e9e75-4c80-46fd-b183-b20c51f2ba37,be8a25ef-0ce9-4b18-aa51-ea48f81f9e05,zaneta.encarnacion@museumofus.org,Bounced,zaneta,encarnacion
3911,a68dda06-f3ac-4e7e-8fee-46644ee269b5,50f273fe-1db6-49eb-8992-e9e243400d26,zawadski.jana@hipsandiego.org,Bounced,zawadski,jana
3912,15ced247-65b2-41ea-9eca-aec414c9a627,e81397b6-3a98-442e-ae04-f801e6c9ac96,zehui.tan@accef.net,Bounced,zehui,tan
3913,369f081b-db7a-4e85-b6f2-1b1193e3b015,f43a3fcf-398a-4588-a9a5-d5c4fb96096e,zeke.valtz@poweroflove.org,Bounced,zeke,valtz

In [11]:
df_delivered2

,id,contactId,contactEmail,status,contactFirstName,contactLastName
0,fb00d1f2-5c8b-4e91-8992-8eb160ff18a3,d2f02cff-fa3a-462a-9d92-6979a7a37dbc,adam.shindler@sdccs.org,Delivered,adam,shindler
1,909f3930-554f-4ae4-959d-d51941653881,27dca666-41cf-4f93-8eb0-5d38453d8f3d,agnes.parks@sharp.com,Delivered,agnes,parks
2,ab682dd9-6875-410a-946e-227f1dfbbd6d,aa94e562-3df3-434c-867e-e01c9d4c8447,alexandria.moffat@walksandiego.org,Delivered,alexandria,moffat
3,030b49c2-2332-4a96-b4c3-c75b1d770378,20ffdf26-0d56-41c9-9a46-4f6ec87775ca,alex.chimon@nu.edu,Delivered,alex,chimon
4,12f77d16-a441-41f4-beb7-e3b2725d319c,adfe1595-bbbe-40de-9e4d-297895d778d1,alexis.o'banion@bpoc.org,Delivered,alexis,o'banion
...,...,...,...,...,...,...
545,efdf0474-86e7-4acf-a80a-ece0e678593b,5c4ffc74-02ef-4990-80b4-eca664062d22,steven.johnson@nu.edu,Clicked,steven,johnson
546,b7ad368d-fc16-4294-a76e-b7fa8de66406,38cedeab-17e5-4a05-a10f-3f2543212f3e,susan.green@sharp.com,Clicked,susan,green
547,b5c16afc-a5a7-4797-b27f-ec83b0d1cadc,58413455-6074-4cf8-8f66-f1b66c48cc39,tami.bereki@sdaihc.org,Clicked,tami,bereki
548,94ee84ce-c9e1-4f3a-ac1f-055ff4b2cc55,7f90a582-be69-4f71-a934-c061f42e206b,thomas.topuzes@nu.edu,Clicked,thomas,topuzes
549,2a3ac9f7-de3f-4390-8e08-1708722ee15f,157edfa2-f5cc-42c6-9377-00e02f9ce7a7,tony.teravainen@teamstepusa.org,Clicked,tony,teravainen

In [12]:
df_clicked2

,id,contactId,contactEmail,status,contactFirstName,contactLastName
0,92abbb2e-5d72-40e9-92ef-d572640d3c14,8aaa60db-473b-46c9-9b7b-c8d55e540d83,albert.oriol@rchsd.org,Clicked,albert,oriol
1,1d3084d1-e5e8-46b2-832a-2ca499eec2b5,7554061d-618b-4756-b8a6-df137ae9605d,andrew.md@rchsd.org,Clicked,andrew,md
2,86b39a63-b282-4c22-b958-504f189affc3,40052f23-a0e3-4cd2-a248-5cb1c52b9659,angela.baldasare@nu.edu,Clicked,angela,baldasare
3,269afae1-9aef-4fb4-96dd-ea13b1c9b751,33f6bdd7-2e72-4556-87ec-56bc2a1d4998,angela.vieira@rchsd.org,Clicked,angela,vieira
4,5d3292ab-a1e5-40ee-aac6-a828c64028e1,a1843145-4bce-46bb-aed8-64668039d7dd,ann.wieczorek@neighbor.org,Clicked,ann,wieczorek
...,...,...,...,...,...,...
59,efdf0474-86e7-4acf-a80a-ece0e678593b,5c4ffc74-02ef-4990-80b4-eca664062d22,steven.johnson@nu.edu,Clicked,steven,johnson
60,b7ad368d-fc16-4294-a76e-b7fa8de66406,38cedeab-17e5-4a05-a10f-3f2543212f3e,susan.green@sharp.com,Clicked,susan,green
61,b5c16afc-a5a7-4797-b27f-ec83b0d1cadc,58413455-6074-4cf8-8f66-f1b66c48cc39,tami.bereki@sdaihc.org,Clicked,tami,bereki
62,94ee84ce-c9e1-4f3a-ac1f-055ff4b2cc55,7f90a582-be69-4f71-a934-c061f42e206b,thomas.topuzes@nu.edu,Clicked,thomas,topuzes
63,2a3ac9f7-de3f-4390-8e08-1708722ee15f,157edfa2-f5cc-42c6-9377-00e02f9ce7a7,tony.teravainen@teamstepusa.org,Clicked,tony,teravainen

In [13]:
df_unsubscribed2

,id,contactId,contactEmail,status,contactFirstName,contactLastName
0,46a21805-c1d2-4996-8d9f-b7e23ed8e3af,4d103b7d-5298-4c53-a0b9-dd46d2fb3fbc,jenna.plante@tmi-inc.org,Unsubscribed,jenna,plante

In [17]:
import pandas as pd

# Add campaign labels
df_delivered["campaign"] = "campaign_1"
df_bounced["campaign"] = "campaign_1"
df_clicked["campaign"] = "campaign_1"
df_unsubscribed["campaign"] = "campaign_1"

df_delivered2["campaign"] = "campaign_2"
df_bounced2["campaign"] = "campaign_2"
df_clicked2["campaign"] = "campaign_2"
df_unsubscribed2["campaign"] = "campaign_2"

# Combine all dataframes
master_df = pd.concat(
    [
        df_delivered,
        df_bounced,
        df_clicked,
        df_unsubscribed,
        df_delivered2,
        df_bounced2,
        df_clicked2,
        df_unsubscribed2
    ],
    ignore_index=True
)

master_df = master_df.set_index("id")

master_df

,contactId,contactEmail,status,contactFirstName,contactLastName,campaign
id,,,,,,
2d5d4c7f-1ec5-432c-b436-e2821d343d37,4b5557b7-4a29-4a9d-89bf-3b09734128cc,aaron.pingel@rihwtf.com,Delivered,aaron,pingel,campaign_1
50437fbc-4848-4bbf-881d-77194c3f5693,ecf617db-9868-4c07-881c-a56553620c0d,adam.falk@borderpartnership.org,Delivered,adam,falk,campaign_1
6b71c605-b675-4567-bb0d-e1fef2cece51,0a295aa7-177f-4ea9-a795-0b827f4b9225,aditi.salvi@realitychangers.org,Delivered,aditi,salvi,campaign_1
b62d3813-3760-4515-a4b0-47cadd42cdc4,ca3ba173-ab95-4e25-917c-23bb5f0cc58e,alan.grant@sandiegoriver.org,Delivered,alan,grant,campaign_1
77383381-5498-41c2-8a42-6b0963b53297,4f1c2696-0046-47a9-99e1-97d059ed7cf0,albert.pleskus@sdyc.org,Delivered,albert,pleskus,campaign_1
...,...,...,...,...,...,...
b7ad368d-fc16-4294-a76e-b7fa8de66406,38cedeab-17e5-4a05-a10f-3f2543212f3e,susan.green@sharp.com,Clicked,susan,green,campaign_2
b5c16afc-a5a7-4797-b27f-ec83b0d1cadc,58413455-6074-4cf8-8f66-f1b66c48cc39,tami.bereki@sdaihc.org,Clicked,tami,bereki,campaign_2
94ee84ce-c9e1-4f3a-ac1f-055ff4b2cc55,7f90a582-be69-4f71-a934-c061f42e206b,thomas.topuzes@nu.edu,Clicked,thomas,topuzes,campaign_2
2a3ac9f7-de3f-4390-8e08-1708722ee15f,157edfa2-f5cc-42c6-9377-00e02f9ce7a7,tony.teravainen@teamstepusa.org,Clicked,tony,teravainen,campaign_2
46a21805-c1d2-4996-8d9f-b7e23ed8e3af,4d103b7d-5298-4c53-a0b9-dd46d2fb3fbc,jenna.plante@tmi-inc.org,Unsubscribed,jenna,plante,campaign_2

In [24]:
unsubscribed_names = master_df[master_df["status"] == "Unsubscribed"][
    ["contactFirstName", "contactLastName", "contactEmail", "status"]
]

unsubscribed_names

,contactFirstName,contactLastName,contactEmail,status
id,,,,
46a21805-c1d2-4996-8d9f-b7e23ed8e3af,jenna,plante,jenna.plante@tmi-inc.org,Unsubscribed

In [25]:
master_df[
    (master_df["contactFirstName"].str.lower() != "jenna") &
    (master_df["contactLastName"].str.lower() != "plante")
]

,contactId,contactEmail,status,contactFirstName,contactLastName,campaign
id,,,,,,
2d5d4c7f-1ec5-432c-b436-e2821d343d37,4b5557b7-4a29-4a9d-89bf-3b09734128cc,aaron.pingel@rihwtf.com,Delivered,aaron,pingel,campaign_1
50437fbc-4848-4bbf-881d-77194c3f5693,ecf617db-9868-4c07-881c-a56553620c0d,adam.falk@borderpartnership.org,Delivered,adam,falk,campaign_1
6b71c605-b675-4567-bb0d-e1fef2cece51,0a295aa7-177f-4ea9-a795-0b827f4b9225,aditi.salvi@realitychangers.org,Delivered,aditi,salvi,campaign_1
b62d3813-3760-4515-a4b0-47cadd42cdc4,ca3ba173-ab95-4e25-917c-23bb5f0cc58e,alan.grant@sandiegoriver.org,Delivered,alan,grant,campaign_1
77383381-5498-41c2-8a42-6b0963b53297,4f1c2696-0046-47a9-99e1-97d059ed7cf0,albert.pleskus@sdyc.org,Delivered,albert,pleskus,campaign_1
...,...,...,...,...,...,...
efdf0474-86e7-4acf-a80a-ece0e678593b,5c4ffc74-02ef-4990-80b4-eca664062d22,steven.johnson@nu.edu,Clicked,steven,johnson,campaign_2
b7ad368d-fc16-4294-a76e-b7fa8de66406,38cedeab-17e5-4a05-a10f-3f2543212f3e,susan.green@sharp.com,Clicked,susan,green,campaign_2
b5c16afc-a5a7-4797-b27f-ec83b0d1cadc,58413455-6074-4cf8-8f66-f1b66c48cc39,tami.bereki@sdaihc.org,Clicked,tami,bereki,campaign_2
94ee84ce-c9e1-4f3a-ac1f-055ff4b2cc55,7f90a582-be69-4f71-a934-c061f42e206b,thomas.topuzes@nu.edu,Clicked,thomas,topuzes,campaign_2
2a3ac9f7-de3f-4390-8e08-1708722ee15f,157edfa2-f5cc-42c6-9377-00e02f9ce7a7,tony.teravainen@teamstepusa.org,Clicked,tony,teravainen,campaign_2